### ISSUE TITLE
about the code...

### ISSUE THREAD

**Issue by amiltonwong** [yanx27/PointASNL#1]
Hi, @yanx27 ,

Congratulations on the acceptance of your work in the coming CVPR. When will the code be released? Is the code based on your previous framework [Pointnet_Pointnet2_pytorch](https://github.com/yanx27/Pointnet_Pointnet2_pytorch)?

THX!

**Comment by yanx27** [comment]
Hi, @amiltonwong thank you for your attention. Codes maybe release after conference, and our codes based on Tensorflow, because it needs CUDA  accelerate in semantic segmentation.

**Comment by yanx27** [comment]
The code is open source now ~
