### ISSUE TITLE
about sampling

### ISSUE THREAD

**Issue by longmalongma** [yanx27/PointASNL#13]
When I run:
python train_semantic_kitti_grid1.py --log_dir PointASNL_grid,I meet this error:

    from metrics import IoU_from_confusions
ImportError: cannot import name 'IoU_from_confusions'

Is IoU_from_confusions right? what the vision of metrics?

**Comment by yanx27** [comment]
@longmalongma Hi, the function used [here](https://github.com/yanx27/PointASNL/blob/5c2854172ddfa15e3000170a63fb8ff069d9876c/utils/metrics.py#L119)

**Comment by longmalongma** [comment]
> @longmalongma Hi, the function used [here](https://github.com/yanx27/PointASNL/blob/5c2854172ddfa15e3000170a63fb8ff069d9876c/utils/metrics.py#L119)

sorry, I forget it!
