### ISSUE TITLE
How do you visualize the segmentation results on semantickitti dataset?

### ISSUE THREAD

**Issue by longmalongma** [yanx27/PointASNL#14]
How do you visualize the segmentation results ｏｎ semantickitti dataset? Can you provide visualization code for segmentation results?

**Comment by yanx27** [comment]
Hi @longmalongma , I use Open3D for visualization in paper. The codes for visualization is somehow messy, I will update in the future. Actually, our code already shown codes for visualization [here](https://github.com/yanx27/PointASNL/blob/5c2854172ddfa15e3000170a63fb8ff069d9876c/SemanticKITTI/test_semantic_kitti.py#L182), but it needs to be opened by MeshLab. If you have interest, you can modify visualized codes from it.

**Comment by longmalongma** [comment]
> Hi @longmalongma , I use Open3D for visualization in paper. The codes for visualization is somehow messy, I will update in the future. Actually, our code already shown codes for visualization [here](https://github.com/yanx27/PointASNL/blob/5c2854172ddfa15e3000170a63fb8ff069d9876c/SemanticKITTI/test_semantic_kitti.py#L182), but it needs to be opened by MeshLab. If you have interest, you can modify visualized codes from it.

Thanks, after I have trained, I will try to test and visualize it.

**Comment by longmalongma** [comment]
> Hi @longmalongma , I use Open3D for visualization in paper. The codes for visualization is somehow messy, I will update in the future. Actually, our code already shown codes for visualization [here](https://github.com/yanx27/PointASNL/blob/5c2854172ddfa15e3000170a63fb8ff069d9876c/SemanticKITTI/test_semantic_kitti.py#L182), but it needs to be opened by MeshLab. If you have interest, you can modify visualized codes from it.

Thanks, after I have trained, I will try to test and visualize it.
