### ISSUE TITLE
about the number of sample point

### ISSUE THREAD

**Issue by longmalongma** [yanx27/PointASNL#15]
Thanks your great work,ｙour work helps me a lot.
I can set batch size to 12 using one rtx2080 for my own model.I see that the number of your sample point is that:1280,320,80,40. Do you mean let me increase the number of sample points to improve performance more in my network?
By the way,Do you think the same network sampled on different datasets S3DIS and Semantickitti should have different number of sample points? Because the number of pints in Semantickitti is 10240, and the number of pints in s3dis is 4096.

**Comment by yanx27** [comment]
Hi, @longmalongma , using more point as input can partly improve the performance (i.e., using 20480 points rather than 10240). The sampled points of each layer should be fixed by certain ratio (i.e., 0.25 or 0.1), which is a hyper-parameter and needs to be finely adjusted :)

**Comment by longmalongma** [comment]
> Hi, @longmalongma , using more point as input can partly improve the performance (i.e., using 20480 points rather than 10240). The sampled points of each layer should be fixed by certain ratio (i.e., 0.25 or 0.1), which is a hyper-parameter and needs to be finely adjusted :)

Thanks for your reply. You mean the number of sampling points should be fixed on different datasets with different input points? Now I have a question.
Should the number of sample points increase with the number of input points in different data sets?

**Comment by tangbohu** [comment]
Thanks for the kind answer! 

Could you share the detailed sample points on S3DIS and SCANNET, for classifcation and for semantic segmentation? Thanks again!
