### ISSUE TITLE
 How to visualize the segmentation results on semantickitti dataset in train_semantic_kitti_grid.py? 

### ISSUE THREAD

**Issue by longmalongma** [yanx27/PointASNL#19]
Hi,How to visualize the segmentation results on semantickitti dataset in test_semantic_kitti_grid1.py? like test_semantic_kitti.py that .obj files can be saved. 
Can you update test_semantic_kitti_grid1.py  so that it can visualize the split results

**Comment by yanx27** [comment]
@longmalongma Hi, could you use official api of semkitti [here](https://github.com/PRBonn/semantic-kitti-api/blob/master/visualize.py) for visualization, which can directly use our prediction outputs.
