### ISSUE TITLE
question about variable "smpws"

### ISSUE THREAD

**Issue by amiltonwong** [yanx27/PointASNL#2]
Hi, @yanx27 ,

Thanks a lot for releasing such useful package. When reading the code, I found a variable "[smpws_pl](https://github.com/yanx27/PointASNL/blob/master/models/pointasnl_sem_seg.py#L14)" but cannot figure out its meaning. Would does the variable "smpws" mean? Does it mean remission value?

THX!

**Comment by yanx27** [comment]
@amiltonwong Hi,  'smpws_pl'  is used to record weight of each point, because we use weighted cross-entropy loss. It also masks point we don't need to calculate loss.

**Comment by amiltonwong** [comment]
@yanx27, thanks~
