### ISSUE TITLE
What is the difference between visualize_voxels.py and visualize_voxels.py? 

### ISSUE THREAD

**Issue by longmalongma** [yanx27/PointASNL#22]
Hi,thanks for your great work and your help, after I run test_semantic_kitti_grid.py, Which file should I use to visualize the ｓｅｇmentation result? visualize.py or visualize_voxels.py? What is the difference between visualize_voxels.py and visualize_voxels.py?

**Comment by yanx27** [comment]
@longmalongma Hi, you should use visualize.py, visualize_voxels.py is used for semantic scene completion task.

**Comment by longmalongma** [comment]
> @longmalongma Hi, you should use visualize.py, visualize_voxels.py is used for semantic scene completion task.

ok,thanks.
