### ISSUE TITLE
about mapped_content in semantic_kitti_dataset.py

### ISSUE THREAD

**Issue by amiltonwong** [yanx27/PointASNL#3]
Hi, @yanx27 ,

It's found that
[mapped_content](https://github.com/yanx27/PointASNL/blob/master/SemanticKITTI/semantic_kitti_dataset.py#L8-L13) is different to the official [one](https://github.com/yanx27/PointASNL/blob/master/SemanticKITTI/semantic-kitti.yaml#L72) provided by SemanticKITTI benchmark. How did you compute the mapped_content?

THX!

**Comment by yanx27** [comment]
Hi, @amiltonwong, 

We only calculate the content number in training set, which will not influence final result :)
