### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by DCNSW** [yanx27/PointASNL#34]
Hello, yanx27, thanks for your great work and the release of code.

I notice that the training time of first epoch is some kind longer than the following epochs by using your code of tensorflow version. I guess it is because you have cached all batchs of data in the first epoch,  is that true? 

Can I reimplement this operation with pytorch?

Thanks for your advice.  @yanx27

**Comment by tangbohu** [comment]
> Hello, yanx27, thanks for your great work and the release of code.
> 
> I notice that the training time of first epoch is some kind longer than the following epochs by using your code of tensorflow version. I guess it is because you have cached all batchs of data in the first epoch, is that true?
> 
> Can I reimplement this operation with pytorch?
> 
> Thanks for your advice. @yanx27

Dear @hudingchang, 

Have you reimplemented the code with pytorch? Would you mind sharing it with me (tangbohutbh@gmail.com)?
Thanks!
