### ISSUE TITLE
Why ablation study has different result?

### ISSUE THREAD

**Issue by swzaaaaaaa** [yanx27/PointASNL#42]
@yanx27 
我自己测试的是这样：
PL only-----93.1
PNL only-----92.5???????

**Comment by yanx27** [comment]
Hi @swzaaaaaaa , thanks for your attention. How did you implement PL only and PNL only?

**Comment by swzaaaaaaa** [comment]
PL中我把pnl注释了，因为最后要加pnl的结果，然后就不加了，只用Pl的结果



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 23, 2021 14:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yanx27/PointASNL] Why ablation study has different result? (#42)




 
Hi @swzaaaaaaa , thanks for your attention. How did you implement PL only and PNL only?

**Comment by yanx27** [comment]
HI, @swzaaaaaaa , if you correctly implemented it, I currently have no idea about this issue. I guess this may cause by slight differences between the released codes and the codes conducting ablations.  For example, the data augmentation and learning rate decay are different from those in the paper. Also, this problem may cause by the huge randomness of experiment results. During my evaluation, the code using PL+PNL can achieve 93.6 sometimes, but will usually around 93.  If I have time in the future, I will double-check it and give you the answer.

**Comment by swzaaaaaaa** [comment]
请问你有单独消融实验PL模块的代码吗，我在我电脑试试



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 23, 2021 14:44 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yanx27/PointASNL] Why ablation study has different result? (#42)




 
HI, @swzaaaaaaa , if you correctly implemented it, I currently have no idea about this issue. I guess this may cause by slight differences between the released codes and the codes conducting ablations.  For example, the data augmentation and learning rate decay are different from those in the paper. Also, this problem may cause by the huge randomness of experiment results. During my evaluation, the code using PL+PNL can achieve 93.6 sometimes, but will usually around 93.  If I have time in the future, I will double-check it and give you the answer.

**Comment by yanx27** [comment]
The code is a bit too old, I need to look for it. . .

**Comment by swzaaaaaaa** [comment]
好的，那就麻烦你找找了，请问最近还在研究这个方向吗，在分类上有没有好的一些建议，谢谢



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 23, 2021 14:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yanx27/PointASNL] Why ablation study has different result? (#42)




 
The code is a bit too old, I need to look for it. . .

**Comment by yanx27** [comment]
I don't think this is a suitable place to discuss this topic :) You can send your questions or WetChat to my email.  --|

**Comment by swzaaaaaaa** [comment]
你好，这是我的微信s1362745408&nbsp;&nbsp;



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 23, 2021 14:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yanx27/PointASNL] Why ablation study has different result? (#42)




 
I don't think this is a suitable place to discuss this topic :) You can send your questions or WetChat to my email.  --|
