### ISSUE TITLE
 Performance issues in SemanticKITTI/semantic_kitti_dataset_grid.py(P2)

### ISSUE THREAD

**Issue by DLPerf** [yanx27/PointASNL#44]
Hello,I found a performance issue in the definition of `init_input_pipeline` ,
SemanticKITTI/semantic_kitti_dataset_grid.py,
[self.train_data = self.train_data.map](https://github.com/yanx27/PointASNL/blob/5c910b609323fc9bfa259c123c7aeb5dc385f52a/SemanticKITTI/semantic_kitti_dataset_grid.py#L368) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

The same issues also exist in [self.test_data = self.test_data.map](https://github.com/yanx27/PointASNL/blob/5c910b609323fc9bfa259c123c7aeb5dc385f52a/SemanticKITTI/semantic_kitti_dataset_grid.py#L370) ,
[self.val_data = self.val_data.map](https://github.com/yanx27/PointASNL/blob/5c910b609323fc9bfa259c123c7aeb5dc385f52a/SemanticKITTI/semantic_kitti_dataset_grid.py#L369)

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by yanx27** [comment]
@DLPerf Thanks for your attention.  I'm exactly too busy now, and you are more than welcome to create a PR :)
