### ISSUE TITLE
Performance issues in /ScanNet (by P3)

### ISSUE THREAD

**Issue by DLPerf** [yanx27/PointASNL#46]
Hello! I've found a performance issue in your project: `batch()` should be called before `map()`, which could make your program more efficient. Here is [the tensorflow document](https://tensorflow.google.cn/guide/data_performance?hl=zh_cn#vectorized_mapping) to support it.

Detailed description is listed below:

- /train_scannet_grid.py: `train_data.batch(FLAGS.batch_size, drop_remainder=True)`[(here)](https://github.com/yanx27/PointASNL/blob/5b3f4d274358bd3116db995afea274455ece6530/ScanNet/train_scannet_grid.py#L146) should be called before `train_data.map(map_func=map_func, num_parallel_calls=dataset.num_threads)`[(here)](https://github.com/yanx27/PointASNL/blob/5b3f4d274358bd3116db995afea274455ece6530/ScanNet/train_scannet_grid.py#L145).
- /train_scannet_grid.py: `val_data.batch(FLAGS.batch_size, drop_remainder=True)`[(here)](https://github.com/yanx27/PointASNL/blob/5b3f4d274358bd3116db995afea274455ece6530/ScanNet/train_scannet_grid.py#L154) should be called before `val_data.map(map_func=map_func, num_parallel_calls=dataset.num_threads)`[(here)](https://github.com/yanx27/PointASNL/blob/5b3f4d274358bd3116db995afea274455ece6530/ScanNet/train_scannet_grid.py#L153).
- /test_scannet_grid.py: `val_data.batch(FLAGS.batch_size, drop_remainder=True)`[(here)](https://github.com/yanx27/PointASNL/blob/5b3f4d274358bd3116db995afea274455ece6530/ScanNet/test_scannet_grid.py#L463) should be called before `val_data.map(map_func=map_func, num_parallel_calls=dataset.num_threads)`[(here)](https://github.com/yanx27/PointASNL/blob/5b3f4d274358bd3116db995afea274455ece6530/ScanNet/test_scannet_grid.py#L462).

Besides, you need to check the function called in `map()`(e.g., `map_func` called in `val_data.map(map_func=map_func, num_parallel_calls=dataset.num_threads)`) whether to be affected or not to make the changed code work properly. For example, if `map_func` needs data with shape (x, y, z) as its input before fix, it would require data with shape (batch_size, x, y, z).

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by yanx27** [comment]
Please feel free for creating a PR :)
