### ISSUE TITLE
about the evaluation performance on sequence08 of SemanticKITTI dataset

### ISSUE THREAD

**Issue by amiltonwong** [yanx27/PointASNL#6]
Hi, @yanx27 

I perform the evaluation on sequence08 of SemanticKITTI dataset by command:
`python test_semantic_kitti.py --model_path log/PointASNL_SemanticKITTI/latest_model.ckpt`. It takes almost 4 days to finish the evaluation. Is this inference time normal or not? My system configuration is a Titan Xp GPU and CUDA 10.0 installed.

THX!

**Comment by yanx27** [comment]
@amiltonwong Hi, the code `python test_semantic_kitti.py` uses small sliding window on raw point clouds, so it's relatively slow, you can try smaller voting number if you are time limited. Furthermore, we already update `python train_semantic_kitti_grid.py` and  `python test_semantic_kitti_grid.py`, which is training and testing on grid sampled sub-point clouds and finally reproject prediction to raw point clouds, and it achieves better result of around 52% with several times efficiency. It will cost 1-2 days for training and 0.5 day for evaluation on sequence08 :)

**Comment by amiltonwong** [comment]
@yanx2, thanks a lot. I'll have a try in train_semantic_kitti_grid.py and test_semantic_kitti_grid.py

**Comment by kxhit** [comment]
@yanx27  Hi! Thanks for sharing your code. 
I notice that you achieved 62.3% IoU on [SemanticKITTI benchmark](https://competitions.codalab.org/competitions/20331#results). Is there any new paper with that result? I'm looking forward to knowing how the algorithm is designed. Thanks a lot!
