### ISSUE TITLE
Problem about line 150 in utils/pointasnl_util.py

### ISSUE THREAD

**Issue by yokinglou** [yanx27/PointASNL#8]
```
new_group_weights = tf_util.conv2d(new_group_features, c, [1, 1],
                                                           padding='VALID', stride=[1, 1],
                                                           bn=bn, is_training=is_training,
                                                           scope='mlp2_%d' % (i), bn_decay=bn_decay, 
                                                           weight_decay=weight_decay,
                                                           activation_fn=activation)
```
Why the output of conv2d is new_group_weights instead of new_group_features? In each loop,  the new_group_features are connected to new_group_weights which are not updated progressively.

**Comment by yanx27** [comment]
Hi @yokinglou, thanks for your attention. You are right. It is true that because of a typo, there is one less MLPs when calculating the weight, but this does not affect the final result. Now the code has been fixed! Thank you :)
